package ch.cern.cms.daq.expertcontroller.datatransfer;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Recovery request DTO. Defines what is
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RecoveryRequest {

    /**
     * Id of the condition that is a problem (generated by client)
     */
    private Long problemId;

    private String problemTitle;

    private String problemDescription;

    private boolean withInterrupt;

    private boolean isSameProblem;

    private boolean withPostponement;

    private List<RecoveryRequestStep> recoverySteps;

    public String toString() {
        return new StringBuilder()
                .append("[").append(problemId)
                .append(": ").append(problemTitle)
                .append("]").toString();

    }

}
